### ISSUE TITLE
Add MNP variant type?

### ISSUE THREAD

**Issue by jasonbwarner** [davidebolo1993/VISOR#10]
Hi, would you be able to add a new mutation type, MNP,  to HACk? The MNP would be such that reference and alternate sequences are of the same length and are greater than 1.

**Comment by davidebolo1993** [comment]
Hi @jasonbwarner,

That indeed would be possibile. Would you like to specify the variants sequence in the input BED or should this sequence be generated at random by HACk ?

**Comment by jasonbwarner** [comment]
Great! I would be specifying the variant sequencing in the input BED.

**Comment by davidebolo1993** [comment]
Sure. I'll add this as soon as possible, ideally within the next 2 weeks.

Best,

Davide

**Comment by davidebolo1993** [comment]
Hi @jasonbwarner,

Just dded MNP variants in VISOR. I've added an example on how to generate a MNP variant in Examples/HACk.bed (last line). I've tested this on a small genome and works just fine. Let me know if I can help further.

Best,

Davide
