### ISSUE TITLE
Feature Request: Add --length-max option

### ISSUE THREAD

**Issue by tjiangHIT** [davidebolo1993/VISOR#12]
Hello @davidebolo1993 

VISOR uses pbsim to perform long-read simulation, and the default maximum length of read is 25 kbp (CLR). It seems enough for the practice of generating long-read which mean length smaller than 25 kbp. However, when simulate long-reads which the mean read length over 25 kbp, an error will be raised by the maximum length in pbsim. Moreover, this default maximum length is not in accordance with the real long-read sequencing technologies, where the longest read length has achieved over 100 kbp. So it would be of great help that add a new --length-max option in order to set the maximum length of long-reads.

Thank you.
Tao

**Comment by davidebolo1993** [comment]
Hi @tjiangHIT, 

I've added the --maxlength, --minlength and --sdlength parameters to VISOR LASeR for the fine tuning of  long-read simulations. This should work. Feel free to reopen if I missed something.

Cheers,

Davide

**Comment by davidebolo1993** [comment]
Hi @tjiangHIT,

the new version of VISOR uses Badread for simulations. I've tested cuteSV on simulated data and it works fine. Maybe you want to have a look for yourself.

Best,

Davide

**Comment by tjiangHIT** [comment]
> Hi @tjiangHIT,
> 
> the new version of VISOR uses Badread for simulations. I've tested cuteSV on simulated data and it works fine. Maybe you want to have a look for yourself.
> 
> Best,
> 
> Davide

Great News! I'll check.
Best,
Tao
