### ISSUE TITLE
Major update coming

### ISSUE THREAD

**Issue by davidebolo1993** [davidebolo1993/VISOR#13]
This is just to let VISOR's users know that a major update is coming, ideally within one month. In its current form, VISOR works just fine but I feel that part of its code has to be refined (e.g. most calls to subprocesses avoided) and new features have to be added. I will also try to implement different read-simulators in VISOR LASeR, so that users can choose which one to use. Feel free to add your suggestions.

**Comment by davidebolo1993** [comment]
I've by now reworked HACk and SHORtS, which are faster and include new features (SHORtS can simulate multiple single cells, some from a reference clone for instance). Maybe it's worth adding RG ID in simulated BAM, as it seems few SV callers require this (https://github.com/tjiangHIT/cuteSV/issues/20#issuecomment-743654177).

**Comment by biozzq** [comment]
Hi @davidebolo1993 

If avaialble, could you add this feature (https://github.com/davidebolo1993/VISOR/issues/11) to the upcoming version.

**Comment by davidebolo1993** [comment]
Also adding -Y to minimap2 alignment with VISOR LASER (https://github.com/tjiangHIT/cuteSV/issues/20#issuecomment-744185516)

**Comment by davidebolo1993** [comment]
I'm done with the major changes to all the modules.
@biozzq, long-read simulations are now performed using Badread. This solves #11, as Badread stores regions used for simulations in the FASTQ header (and you can will find this information in the read name of the BAM file generated by LASeR). Long-read simulation is overall slower with Badread (but VISOR implements a parallel version of Badread), but it gives users control over a series of useful parameters (and users can also train their error and quality score model - I think this can be adjusted also for #8).
BWA is no more supported in VISOR, which now uses minimap2 for paired-end short-read alignments as well (it is tens of time faster and has similar accuracy from my preliminary tests). 
All the code has been reworked and calls to external bash scripts removed.
If you notice any bug, please get in touch !

**Comment by davidebolo1993** [comment]
Of course, have a look at the documentation before running VISOR. Some parameters have changed since the previous version.
