### ISSUE TITLE
HACk - Index error for reciprocal translocation

### ISSUE THREAD

**Issue by cdelahaye** [davidebolo1993/VISOR#15]
Hello,
First, thank you for your great work with this very interesting and helpful package !
I think I have spotted a little bug in HACk module for "reciprocal translocation".

An example of the error (I ran it with very first bases of *E. coli* genome):
`NC_000913.3	8	15	reciprocal translocation	h1:NC_000913.3:20:forward:forward	0`  
Here is what I get (I put spaces between translocated regions for easier reading):
`AGCTTTT CATTCTGA CTGCA ACGGGCAA TATGTCTCTGTGTGGATTAAAAAAAGAGTGTCT`
`AGCTTTT ACGGGCAA CTGCA CATTCTGA _ATGTCTCTGTGTGGATTAAAAAAAGAGTGTCT`
The translocation goes well but there is a missing base (noted `_`) after the second translocation.

I could fix this with few modifications in the source code, in `VISOR/HACk/HACk.py`:

line 674: `                                lastbase=int(column5[2])+(x.end-x.start)` -> `lastbase=int(column5[2])+(x.end-x.start+1)`
line 714: `					d[column5[0]][column5[1]] = [(firstbase+1, lastbase+1, newtype, transeq,randomseq)]` -> `                                        d[column5[0]][column5[1]] = [(firstbase+1, lastbase, newtype, transeq,randomseq)]`
line 718: `					d[column5[0]][column5[1]].append((firstbase+1, lastbase+1, newtype, transeq,randomseq))` -> `                                     	d[column5[0]][column5[1]].append((firstbase+1, lastbase, newtype, transeq,randomseq))`

**Comment by davidebolo1993** [comment]
Hi @cdelahaye,

thanks for reporting. Can you link the E. coli genome used and share your bed with me? 

Thanks,

Davide

**Comment by cdelahaye** [comment]
Sure !
The genome can be found [here](https://www.ncbi.nlm.nih.gov/nuccore/NC_000913.3?report=fasta), I just used it for quick try of your scripts, thus I only used a part of it, and very short bed file.

I forgot to precise in my first message that the first sequence I put is the original genome, and the second one is the HACk output.

[hack_issue.zip](https://github.com/davidebolo1993/VISOR/files/6100656/hack_issue.zip)

**Comment by davidebolo1993** [comment]
Hi @cdelahaye,

Thanks a lot. I (correctly) incremented the index in the final dictionary without extracting the entire corresponding sequence though. The quick-fix you proposed works fine (tested with your example). I've just pushed the changes to the master branch. 

Thanks,

Davide

**Comment by davidebolo1993** [comment]
BTW, let me know if you notice any other bug during your tests.

Thanks,

Davide
