### ISSUE TITLE
HACk - Ignores index out of bounds

### ISSUE THREAD

**Issue by vrohnie** [davidebolo1993/VISOR#16]
Hi, thanks for your work.

We've automatically generated BED files for HACk, including some more complex Variants.

Due to a bug on our side, I've realized that HACk doesn't throw an error if the region given in the bed file is located after the chromosome length.
It rather does nothing or inserts the sequence at the end.

I think this should be corrected to throwing something like an Index out of bounds, error.

Best regards,
Veronika

BED examples :

NC_000913.3	2004441	2007026	translocation copy-paste	h1:NC_000913.3:5642652:forward	0
NC_000913.3	5641652	5642652	deletion	None	0

Tested with E.coli sequence from NCBI accession NC_000913.3, with VISOR HACk v1.1, provided through the latest docker image.

**Comment by davidebolo1993** [comment]
Hi @vrohnie,

thanks for reporting. You are definitely right. I'll fix this asap.

Best,

Davide

**Comment by davidebolo1993** [comment]
Hi @vrohnie,

this should be fixed through the latest master (and the latest docker image as well). Let me know if I missed something.

Thanks,

Davide
