### ISSUE TITLE
LASeR, no simulated reads

### ISSUE THREAD

**Issue by azure-twilight** [davidebolo1993/VISOR#18]
I use VISOR v1.1 to simulate long reads. There is no error reported in LASeR step but it does not simulate reads, as the final bam file has no information in it. What's wrong with this?

**Comment by davidebolo1993** [comment]
Hi @azure-twilight,

sorry for being late. That's indeed strange. I'm using LASeR quite frequently and this is never happening. Can you elucidate a bit more on your case ? (command line used and stuff like that...).

Thanks,

Davide

**Comment by azure-twilight** [comment]
I use this command for a test: VISOR LASeR -s ins -g ref.fasta -o ins0 --coverage 2 -b LASeR.bed --threads 4
And it runs without errors, but when simulating, it produces .fq files with size 0. 

Lucky I found an old version of VISOR in my evironment and it runs correctly, but I still don't know what happens with the newest version of VISOR.

**Comment by davidebolo1993** [comment]
Any updates on this?

**Comment by davidebolo1993** [comment]
Closing for the time being. Feel free to re-open at anytime.

**Comment by cytham** [comment]
@davidebolo1993 I am having the same issue. Got a bam file containing only the header. 

My command
`VISOR LASeR -g ../resource/human_hs37d5.fasta -s chm1/ -b ../resource/SV_evaluation/SHORtS.LASeR.bed -o 10x_20k_90 --coverage 10 --identity_min 90 --length_mean 20000 --read_type pacbio --threads 40`

Do you have an email for me to send you the fasta, hack and laser beds?

**Comment by davidebolo1993** [comment]
Hi @cytham,

Sure, reach me out @ davidebolognini7@gmail.com. Thanks,

Davide

**Comment by davidebolo1993** [comment]
Just for future reference, this was caused because 0s were specified in SHORtS.LASeR.bed instead of 1s when simulating chromosome-long regions (VISOR LASeR).

**Comment by LYC-vio** [comment]
Hi @davidebolo1993, I met the same issue here, and changing from 0s to 1s didn't help

the HACK and LASeR commands I used were:
```
ref=hs37d5.fa
bed=sim_dup.bed
hapdir=simulated_genome_dup

bed_LASeR=LASeR.bed
cov=40
outdir_LASeR=Reads_dup_${cov}x

VISOR HACk -g ${ref} -b ${bed} -o ${hapdir}
VISOR LASeR -g ${ref} -s ${hapdir} -b ${bed_LASeR} -o ${outdir_LASeR} --coverage ${cov} --threads 16 --fastq --compress
```

The VISOR I used was the v1.1.2 on anaconda
**reference** was downloaded from: ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz
**sim_dup.bed** and **LASeR.bed** were from here: https://github.com/tjiangHIT/cuteSV/tree/master/simulation
I manually changed 0s in column 2 of **LASeR.bed** to 1s, but the output fq file was still empty.

Could you give me some help on this?

Best

**Comment by YihangLin123** [comment]
Has this problem been solved? I have encountered the same issue too.
