### ISSUE TITLE
Assemblytics bed to HACk bed

### ISSUE THREAD

**Issue by agolicz** [davidebolo1993/VISOR#19]
Hi,
I have a .bed file produced by Assemblytics.

The coordinates are as follows:
reference       ref_start       ref_stop        type
chrC01  16417864        16417924        Deletion
chrC01  **883429  883429**  Insertion

As it is a .bed file I assume coordinates are 0-based. I am wondering how to convert Insertion coordinates to HACk BED, were for insertions column 2 is supposed to be: breakpoint-1 and column 3: breakpoint.

Should a corresponding HACk BED be?:

chrC01  16417864        16417924        deletion
chrC01  **883428  883429**  insertion

Thanks!

Agnieszka

Here is a further example of Assemblytics bed: http://assemblytics.com/analysis.php?code=arabidopsis

**Comment by davidebolo1993** [comment]
Hi @agolicz,

yes, in standard BED start coordinates are 0-based (end coordinates are not). For your example (assuming this is a "test.bed" file) from Assemblytics, something like the line below should work:

```bash
awk 'OFS=FS="\t"''{if($4 == "Insertion") print $1, $3-1, $3, $4; else print $0}' test.bed
```

Let me know if I can help further,

Davide

**Comment by agolicz** [comment]
Beautiful! Many thanks. One more question do you have a recommended tool to convert HACk bed to vcf?

**Comment by davidebolo1993** [comment]
Hi @agolicz,

not a tool, but this script [here](https://github.com/davidebolo1993/EViNCe/blob/main/SI00001/workflow/scripts/converter.py) can convert a HACk BED with standard SVs (DEL,DUP,INV,INS,BND) into a VCF that can be in turn used with downstream softwares like [truvari](https://github.com/spiralgenetics/truvari) for benchmarking. Usage is something like:

```bash
python converter.py <input.reference.fasta> <input.hack.bed> <output.hack.vcf>
```

Hope this helps, 

Davide

**Comment by agolicz** [comment]
Perfect, exactly what I was after :).

Agnieszka

**Comment by davidebolo1993** [comment]
Hi @agolicz,

I think this is an issue related to the names used by VISOR in read headers, which are modified to facilitate downstream benchmarking (and debugging, I must say). For the alignment step I think this is not a big issue, because of pairs being read in parallel from 2 (temporary) FASTQ files, but for re-building the initial FASTQ files I guess this can be problematic. If you can share your data, I can try to replicate the issue and dig a bit better into this one as soon as I have time. 

Thanks,

Davide

**Comment by agolicz** [comment]
Thanks, I'll share the files later today.
Do you think it would possible to have an option dump the simulated reads directly to fastq and have fastq along the bam. That would save the hassle of rebuilding...

If you are too busy now, I could modify my local copy and test if you could point me to the part of the code which should be changed.

**Comment by davidebolo1993** [comment]
Yes, that' the idea, basically adding a --fastq flag that stores the fastq in the output folder. 
I think I can have a look into this in the next few days but feel free to test your ideas and get back with suggestions.  


Thanks,

Davide

**Comment by davidebolo1993** [comment]
Hi @agolicz, 

attached a new version of VISOR.py and SHORtS.py. Can you give these a try? 
You need to un-tar the file attached and replace VISOR.py and SHORtS.py in your VISOR folder with the copies attached before re-running setup.py. SHORtS (and LASeR, same stuff, but will be added in the official release) now accepts a --fastq flag that dumps fastq files (r1.fq and r2.fq) to the output folder without changing the previous simulation model. Hopefully, these can be further re-used for testing other aligners. It works on a small test, but maybe needs some refining. 

Thanks,

Davide
[newvers.tar.gz](https://github.com/davidebolo1993/VISOR/files/7293214/newvers.tar.gz)

**Comment by agolicz** [comment]
Seems to have worked fine!

I have one last question regarding coverages (genome size: 764629779 bp).
For SHORtS coverage is exactly as I would expect it:
For --coverage 10
wc -l r1.fq
152696444 r1.fq
>>> float(152696444)/4*2*100/764629779
9.984991965634652

Foe LASeR in the --covarege 5 simulation I got 
cat laser.5x.fq | paste - - - - | cut -f 2 | tr -d '\n' | wc -c
>>> 10376507526/764629779
13.570629618389477

Is the coverage calculation different for long reads (not total bp/genome size)?
I only noticed because LASeR fastq files are much bigger than SHORts.

Agnieszka

**Comment by davidebolo1993** [comment]
Hi  @agolicz,

I can confirm that bamToFastq is causing the issue (well, that's actually not an issue). I guess that bamToFastq do not account for multi-mappings (that is, reads that have a primary alignment as well as supplementary alignments) so that the same read is in the end extracted multiple times. A simple check on the output FASTQ from LASeR and bamToFastq unveil the mistery:

```bash
#true # of reads
grep "^@" laser.fq | wc -l #271879, in my case
# of reads from bamToFastq
grep "^@" bamtofastq.fq | wc -l #367849, in my case
#de-duplicating
grep "^@" bamtofastq.fq | sort | uniq | wc -l #271879, matching ground truth
```

**Comment by davidebolo1993** [comment]
> How many secondary alignments do you normally see in the human genome?

Quite a lot, especially in synthetic datasets containing a lot of SVs. This is also reported [here](https://www.nature.com/articles/s41467-019-11272-z), for instance, but it depends a lot on the parameters used for mapping I have to say.

> It would be great if along the message the bed entries for the skipped variants were also printed. It helps with debugging issues with bed file and possibly producing a final vcf which reflects variants used for haplotype building.

I know but this is not as trivial as it seems, because of how variants are handled internally by HACk. For instance, a standard cut&paste translocation is translated internally into a deletion and an insertion that do not have a corresponding key (entry) in the original BED. A possible solution is to build a second dictionary where each key is the entry in the VCF and the corresponding value a tuple of variants derived from that entry but I'm honestly looking for something more elegant. I'll experiment with possible strategies as soon as I have time.

> Thanks for all the help. VISOR is a great tool and will help us immensely.

Thanks.

Davide

**Comment by agolicz** [comment]
> Hi @agolicz,
> 
> not a tool, but this script [here](https://github.com/davidebolo1993/EViNCe/blob/main/SI00001/workflow/scripts/converter.py) can convert a HACk BED with standard SVs (DEL,DUP,INV,INS,BND) into a VCF that can be in turn used with downstream softwares like [truvari](https://github.com/spiralgenetics/truvari) for benchmarking. Usage is something like:
> 
> ```shell
> python converter.py <input.reference.fasta> <input.hack.bed> <output.hack.vcf>
> ```
> 
> Hope this helps,
> 
> Davide

Hi, I have a quick question about converter.py

I converted mv HACk bed to vcf, but I noticed that for while start position for insertions seems to get updated with +1, this is not the case for deletions. Is there a reason for that? Sample code snippet

```
python converter.py Express617_v1.chrs.fa Assemblytics.INS.DEL.visor.uniq.no.chrs.bed Assemblytics.INS.DEL.visor.uniq.no.chrs.vcf

#Insertion - different start (vcf start = bed start +1, expected behavior)
grep 139536 Assemblytics.INS.DEL.visor.uniq.no.chrs.bed
chrA01  139535  139536  insertion       TTTTTTAAAAAATTTTAAATTTATTCAAATAAAAAAAAAACTTTTGTACAGAGTTTTATCTGCTACCATATTTAAATACAATGAAATGCAAACCAAAAAAAAATATGCTTCTATATCTCTCAAGCTATACTAGCCTCTGTTAAACCAATCCTCCATCATCTTCTCATATTTACCTCTTACCCTCCTTCTCAAAGAAGATATTCTGTTTCTAATGAGCTTATCAAGCCTTGCAATCAGACAGGTAGCTGGCTGCGATGCCTCACCCACTCTTCTCACATTCCTCTCATGCCATAACGCATAAGCCACGGCCTGAAAGCAATAACGCAGTAACACAGTCGAACTCCACTTATGTAAACCCTTCTCAACAATCCGAAGCACTCTATCCCATTTAC  0
grep 139536 Assemblytics.INS.DEL.visor.uniq.no.chrs.vcf
chrA01  139536  var1    N       <INS>   .       PASS    SVTYPE=INS;END=139536;SVLEN=392 GT      1/1

#Deletion - same start (bed start = vcf start, expected behavior)
grep 161804 Assemblytics.INS.DEL.visor.uniq.no.chrs.bed
chrA01  161557  161804  deletion        None    0
grep 161804 Assemblytics.INS.DEL.visor.uniq.no.chrs.vcf
chrA01  161557  var2    N       <DEL>   .       PASS    SVTYPE=DEL;END=161804;SVLEN=-247        GT      1/1

```

**Comment by agolicz** [comment]
I just had a look at the ncbi documentation and it looks like in vcf for INS and DEL it is the 'anchor' which is provided which is the first bp before variant starts, so in fact for both INS and DEL the first bed coordinate should be kept (no +1)?

https://www.ncbi.nlm.nih.gov/variation/tools/reporter/docs/examples

**Comment by agolicz** [comment]
I seem to have gone down coordinate rabbit hole a bit and noticed that different tools seem to handle bed SV coordinates a bit differently...
Just to confirm, for the two attached SVs I would expect the coordinates to be:
Insertion: chr1S 754740078 754740079
Deletion: chr1S 754768762 754768819

Is that correct?
<img width="947" alt="Sample_insertion" src="https://user-images.githubusercontent.com/10213846/142853794-63c6034f-e447-4bdd-a355-eb778fd2e3bb.png">

<img width="950" alt="Sample_deletion" src="https://user-images.githubusercontent.com/10213846/142853922-a5a07601-c69b-4cfb-bcaf-cfb6eeaae7f0.png">

**Comment by davidebolo1993** [comment]
Hi @agolicz,

Because in VISOR INS events are added immediately after the END coordinate specified in your BED, in the corresponding VCF event you should see the END coordinate as POS (which is exactly what I see in your example [here](https://github.com/davidebolo1993/VISOR/issues/19#issuecomment-975353730)). For DEL events, POS and END are the first and last deleted bases. 

Best,

Davide

**Comment by agolicz** [comment]
Yes thanks, I think you are correct. The INS position got me confused. Could you double check if my INS and DEL coordinates based on IGV are correct? Just to make sure I get it now...

Agnieszka

**Comment by davidebolo1993** [comment]
Yes,

they look good to me. Let me know if I can help further.

Thanks,

Davide

**Comment by agolicz** [comment]
Brilliant thanks. I think that should do it!

Agnieszka

**Comment by agolicz** [comment]
Also as a note if anyone ever encounters this thread for the variants pictured above:

Assemblytics output (Assemblytics_structural_variants.bed):
chr1S   754740080       754740080       Assemblytics_w_183750   25377   +       Insertion       0       25377   ptg000015l:1377388-1402765:+    within_alignment
chr1S   754768763       754768820       Assemblytics_w_183752   57      +       Deletion        57      0       ptg000015l:1419021-1419021:+    within_alignment

Corresponding vcf:
chr1S   754740079       svim_asm.INS.33071      C       N   . PASS    SVTYPE=INS;END=754740079;SVLEN=25377    GT      1/1
chr1S   754768762       svim_asm.DEL.34093      N     A       .       PASS    SVTYPE=DEL;END=754768819;SVLEN=-57   GT      1/1

Corresponding HACk bed coordinates:
chr1S   754740078   754740079
chr1S   754768762   754768819
