### ISSUE TITLE
some chromosomes BAM files generated by VISOR LASeR v1.1 were empty

### ISSUE THREAD

**Issue by dxkeac** [davidebolo1993/VISOR#22]
After running VISOR LASeR, some chromosomes BAM files are empty. For example, the size of chr1 BAM file is 8Gb, but chr10 BAM file is 0kb. It is strange.

The command:
VISOR LASeR -g $ref -s $hack -b $laser -o LASER_30x \
--coverage 30 --read_type pacbio --error_model pacbio2016 --qscore_model pacbio2016 --threads 10

Looking forward to your help.

**Comment by davidebolo1993** [comment]
Hi @dxkeac,

sorry that I'm late on this. I cannot replicate this issue and I definitely need those files to give your command a try.

Let me know,

Davide
