### ISSUE TITLE
Release for conda package

### ISSUE THREAD

**Issue by tdido** [davidebolo1993/VISOR#23]
Hello.

I'm working to create a conda package for VISOR to more easily integrate it into our workflows. If all goes well we could add it to bioconda.

Would you mind creating a tag-based release (e.g. v1.1.0) for me to use? I'd rather avoid working from a fork if possible.

**Comment by davidebolo1993** [comment]
Hey @tdido,

thanks. Just added the v1.1 tag in the releases. Let me know if I can help further.

Thanks,

Davide
