### ISSUE TITLE
VISOR SHORtS for simulating pair-end data

### ISSUE THREAD

**Issue by lx-1011** [davidebolo1993/VISOR#28]
Dear @davidebolo1993 ,
Thanks your for this useful tool. I have a question about simulating illumina sequencing data using VISOR SHORtS. Firt, using the same insertion bed file for simulating long-read and short-read sequencing data, i found that most of insertion could not be simulated in short-read data, like that
![image](https://user-images.githubusercontent.com/47030888/202351025-6cae1872-76a2-4959-b22b-a9abb50ce361.png)
![image](https://user-images.githubusercontent.com/47030888/202351159-80d5a289-255e-4ec4-ace9-de84890b9373.png)
![image](https://user-images.githubusercontent.com/47030888/202351332-e65bd45d-b6ec-45a2-858d-3801c5b2bc4f.png)

#VISOR HACk -g ref.fa -b ins.bed -o ./ins.hack.out
#VISOR SHORtS -s ins.hack.out/ -b shorts.laser.simple.chr1.bed -g ref.fa -o ./SR.ins.laser.out --threads 10 --coverage 50
 Do you have any suggestions on that? 
Thank you so much
Lixin

**Comment by davidebolo1993** [comment]
Hey @lx-1011,

I would say that this is expected since short reads have limitations with large SVs and are splitted at breakpoints. Highlighting soft-clipped bases should help.

Let me know if you need help,

Davide
