### ISSUE TITLE
Definition of oriantation region of breakpoints

### ISSUE THREAD

**Issue by infotmatician** [davidebolo1993/VISOR#29]
Hi,
Thank you for developed such a great tool. 
How can I specify variant direction using VISOR according to VCF4.2?
I am a little bit confusued about HACk, when want to generate translocations.
I am trying to do bechmark of SV tools for long reads. 
As an example, 
`
1	10000	30000	reciprocal translocation	h1:20:420000:forward:reverse	0
`
Does this variant should align the left of 20:420000 or right of 20:420000?
Best regards

**Comment by davidebolo1993** [comment]
Hey @infotmatician,

the example line you provide basically substitutes 1:10000-30000 with 20:420000-440000 (length here is 20000) and viceversa. That's what a reciprocal translocation is supposed to do.
A simple script to convert HACk .bed to .vcf is referenced in this issue [here](https://github.com/davidebolo1993/VISOR/issues/19#issuecomment-932316708): this does not cover every possible cases but should be a good starting point. 

Let me know if this helps,

Davide
