### ISSUE TITLE
complex SV types not in list

### ISSUE THREAD

**Issue by jiadong324** [davidebolo1993/VISOR#3]
Hi,

Since you close the last issue, I raise a new one. 

If I understand correctly from your deletion-inversion example, I could put some simple SVs adjacent to each other, and VISOR will produce such specific complex SVs. If so, it has to be created manually, since regions are selected randomly. 

Thanks!

**Comment by davidebolo1993** [comment]
Hi @jiadong324,

Indeed. For the time being, this is something that you can apply to manually-curated SVs. For example, you can generate some random deletions with the included R script and you can than manually edit the final BED adding flanking inversions, if it fits what you want.

Best,

Davide

**Comment by jiadong324** [comment]
@davidebolo1993 Ok, I get it. Thanks!
