### ISSUE TITLE
calculate ground truth copy number profile from HACk.bed

### ISSUE THREAD

**Issue by Jiayi-Wang-Joey** [davidebolo1993/VISOR#30]
Dear Davide, 

Thanks for your great work of VISOR!
We used visor to simulate WGS data in bam format to test if our CNV detection method works good. Now we want to predict the CNV prediction accuracy. Basically, we want to compare the copy number in each position and see if they match. However, I am not sure how to calculate the ground truth copy number profile from HACk.bed where we saved the CNVs. It includes information on CNV types, but no information on copy numbers. I wonder how can we calculate the copy number profile of the simulated data? Thank you very much!

Kind regards,
Jiayi Wang

**Comment by davidebolo1993** [comment]
Hey @Jiayi-Wang-Joey,

sorry for the delay, I'm travelling these days. 
I assume copy numbers here are deletions and tandem duplications. For tandem duplications, you have how many times a segment is duplicated in the hack.bed - this is required at the time of variant generation. For deletions, if you simulated het SVs, you can assume copy number is 1 (I'm assuming human as a reference here). Also, I have a script to convert .bed to .vcf for HACk [here](https://github.com/davidebolo1993/EViNCe/blob/main/SI00001/workflow/scripts/converter.py). You may want to work on this to adjust for your needs.

Let me know if you need further help,

Davide

**Comment by Jiayi-Wang-Joey** [comment]
Thanks Davide!
For me, it is like deletions, insertons, tandem duplications and tandem repetition will all influence the copy number. For tandem duplications, if the 5th column (SV info) says 2, does it mean gain 2 copy numbers? But how do you say the copy number of insertion? 
Thanks again!


Jiayi

**Comment by vilocha** [comment]
Hi Jiayi,

There is a published pipeline called 'perSVade' that calculates prediction/calling accuracy of SV calling methods. 
You may want to have a look:
https://github.com/Gabaldonlab/perSVade

Good luck!
Vicente
