### ISSUE TITLE
Keep old VISOR versions

### ISSUE THREAD

**Issue by LYC-vio** [davidebolo1993/VISOR#32]
Hi,

Is it possible for you to keep some archives of older versions of VISOR on GitHub and Docker? It will be much better to have older versions to use when we meet bugs in latest release, and this can also improve reproducibility

Best

**Comment by davidebolo1993** [comment]
Hey @LYC-vio, 

agree. I'm swamped with many other things these days, but definitely need some time to go over issues at some point. Maybe in 2 weeks or so?

Keep you posted,

Davide
