### ISSUE TITLE
Can VISOR perform SV simulation within a given region?

### ISSUE THREAD

**Issue by vegetableyu** [davidebolo1993/VISOR#36]
Hi，
I wonder whether VISOR can simulate SVs only for a given region, such as MHC region (chr6:28Mbp-34Mbp) ？
Thanks for your time！
Yu

**Comment by davidebolo1993** [comment]
Hey @vegetableyu, absolutely. This requires to specify the SV of interest in the initial .bed file for HACk and add no other variation in any other loci of the genome.
