### ISSUE TITLE
Error models and quality models

### ISSUE THREAD

**Issue by jyw-atgithub** [davidebolo1993/VISOR#37]
Dear @davidebolo1993 , 
I am using VISOR version 1.1.2. The help message of `VISOR LASeR` reported several error models and quality models for simulating long reads. May I know the corresponding technology of each model?  For example, 

|model name|tech|
|---|---|
|nanopore2023 | Minion, R10.4.1 flow cell and Kit 14 ?|

 Thank you!

```bash
--error_model         error model. Can be "nanopore2023", "nanopore2020", "nanopore2018", "pacbio2016", "random" or a model provided by the user using instructions at https://github.com/rrwick/Badread/wiki/Generating-error-and-qscore-models [nanopore2023]
--qscore_model        quality score model. Can be "nanopore2023", "nanopore2020", "nanopore2018", "pacbio2016", "random", "ideal" or a model provided by  the user using instructions at https://github.com/rrwick/Badread/wiki/Generating-error-and-qscore-models [nanopore2023]

```

**Comment by davidebolo1993** [comment]
Hey @jyw-atgithub,

VISOR internally calls [Badread](https://github.com/rrwick/Badread) - you can refer to that page for further info on error and qscore models.

**Comment by jyw-atgithub** [comment]
Thank you!
