### ISSUE TITLE
[Question] generating paired tumor-control samples

### ISSUE THREAD

**Issue by waltergallegog** [davidebolo1993/VISOR#38]
Hello.
I'm interested in the evaluation of somatic SV callers, and due to the lack of benchmarks, I'm planning on using a simulator to generate the test data.
I was wondering if you have considered the use case of generating a tumor-control pair, in which the tumor sample contains additional SVs to those in the control, or if you have any hints/suggestions on how to use VISOR to do so.
Thanks and BR,
Walter.

**Comment by davidebolo1993** [comment]
Hi @waltergallegog,

VISOR can definitely help with this. Ideally, you can simulate a sample with some SVs and add some others in a second sample using [HACk](https://davidebolo1993.github.io/visordoc/usage/usage.html#visor-hack). With this, you will end up with a couple of folders, one with your control haplotypes and one with your tumor haplotypes. You can then simulate reads from those haplotypes with SHORtS/LASeR (short and long reads respectively). You can check out the documentation for some examples. SHORtS and LASeR offer some control over tumor purity which is often found to occur in true-to-life samples.

Hope this helps,

Davide

**Comment by waltergallegog** [comment]
Thanks for the quick and very helpful answer. I will check the suggested documentation.

**Comment by davidebolo1993** [comment]
Also @waltergallegog, a couple of real tumor-control datasets I've worked with in the past:

[COLO829, tumor](https://www.ncbi.nlm.nih.gov/sra/DRX248304%5Baccn%5D)
[COLO829, normal](https://www.ncbi.nlm.nih.gov/sra/DRX248305%5Baccn%5D)
[H2009, tumor](https://www.ncbi.nlm.nih.gov/sra/DRX248305%5Baccn%5D)
[H2009, normal](https://www.ncbi.nlm.nih.gov/sra/DRX248309%5Baccn%5D)
[HCC1954, tumor](https://www.ncbi.nlm.nih.gov/sra/DRX248306%5Baccn%5D)
[HCC1954, normal](https://www.ncbi.nlm.nih.gov/sra/DRX248307%5Baccn%5D)

**Comment by waltergallegog** [comment]
Thanks for the datasets. Have you also worked with somatic SV truth sets by any chance?
I know of the truth sets in the Espejo Valle-Inclan and Arora benchmarks, and the recent truth set by Paulin et al.

**Comment by davidebolo1993** [comment]
Late to this - but leaving here also for future reference: https://www.nist.gov/programs-projects/cancer-genome-bottle
