### ISSUE TITLE
info column for duplication

### ISSUE THREAD

**Issue by stcoh** [davidebolo1993/VISOR#39]
For 'tandem duplication' and 'inverted tandem duplication' from https://github.com/davidebolo1993/VISOR/blob/master/scripts/randomregion.r, is the info column (info[i] <- '2') always gonna be 2? Can a dup be repeated more than 2 times?

**Comment by davidebolo1993** [comment]
hey @stcoh, 

that script generates a template that you can easily modify. You can change that value easily downstream.

Best, 

Davide
