### ISSUE TITLE
Enhance VISOR HACk: Implement aligner selection for improved SV calling comparison

### ISSUE THREAD

**Issue by villena-francis** [davidebolo1993/VISOR#43]
Hi!
One of the variables that is influencing the success/failure of different SV calling methods is the aligner used to generate the BAMs. It would be very very interesting if VISOR HACk would allow to change the aligner (e.g. to LRA) to compare and estimate which one is the most convenient. Would it be possible?

**Comment by davidebolo1993** [comment]
Hi @villena-francis - you can output .fastq files instead and align through your aligner of choice. Would that work?

https://github.com/davidebolo1993/VISOR/blob/11afd676a2bbdcc8eddd586e2f57480c39189044/VISOR/VISOR.py#L142

Best,

Davide

**Comment by villena-francis** [comment]
Of course! Thank you again and sorry for the inconvenience...
