### ISSUE TITLE
ZeroDivisionError: float division by zero when running VISOR SHORtS

### ISSUE THREAD

**Issue by bbunce** [davidebolo1993/VISOR#45]
I am encountering the error below when running the following command, `VISOR SHORtS -s /hack/CYP11B1 -b CYP11B1.shorts.bed -g chr8.fa -o shorts/CYP11B1`. I am using `davidebolo1993/visor:latest` specified in the documentation, although I did have to add bedtools to the PATH before I could use run the commands. Do you know why I might be seeing this error?

```
[26/11/2024 15:33:18][Message] VISOR SHORtS v1.1.2
[26/11/2024 15:33:18][Message] Preparing for bulk simulations with a single clone
[26/11/2024 15:33:18][Message] Processing clone 1
Traceback (most recent call last):
  File "/usr/local/bin/VISOR", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/VISOR/VISOR.py", line 227, in main
    args.func(parser, args)
  File "/usr/local/lib/python3.10/dist-packages/VISOR/VISOR.py", line 296, in run_subtool
    submodule.run(parser,args)
  File "/usr/local/lib/python3.10/dist-packages/VISOR/SHORtS/SHORtS.py", line 1041, in run
    c.fperc=c.cperc/len(c.ffiles) #sample/clone percentage divided equally for each FASTA
ZeroDivisionError: float division by zero
```

**Comment by davidebolo1993** [comment]
Hey @bbunce, hard to tell from this snapshot. Can u share the full dataset? (Also, previous hack command?)

**Comment by bbunce** [comment]
Hi @davidebolo1993, the issue has seemed to have resolved itself. Still using the same commands but not getting the same error.

**Comment by bbunce** [comment]
Hi @davidebolo1993, actually I'm seeing the error again.

**HACK command**
```
docker run --rm -itv $wrkDir:/data -v $refDir:/ref -w $wrkDir $docker VISOR HACk -b $hackBed -g /ref/$refFasta -o $varName/hack
```
**SHORTS command**
```
docker run --rm -itv $wrkDir:/data -v $refDir:/ref -w $wrkDir $docker VISOR SHORtS -s "$varName/hack" -b $shortsBed -g "/ref/$refFasta" -o $varName/shorts
```

### Runs successfully
**HACK bed**
```
8	142876092	142876093	SNP	C	0
8	142876092	142876093	SNP	G	0
```

**SHORTS bed**
```
8	142788622	142963565	100.0	100.0
```

### Error
**HACK bed** HACK command runs successfully
```
17	31162374	31182520	deletion	None	0
17	31182521	31250996	inversion	None	0
17	31250997	31266506	deletion	None	0
```

**SHORTS bed** Encounters ZeroDivisionError: float division by zero Error
```
17	21162374	41266506	100.0	100.0
```
