### ISSUE TITLE
'Namespace' object has no attribute 'func'

### ISSUE THREAD

**Issue by biozzq** [davidebolo1993/VISOR#7]
Dear @davidebolo1993 

After installing VISOR, it's OK when running `VISOR --help`, however it gives me following error when running `VISOR`. Does this affect the results?
```
Traceback (most recent call last):
  File "VISOR", line 11, in <module>
    load_entry_point('VISOR==1.0', 'console_scripts', 'VISOR')()
  File "/lib/python3.7/site-packages/VISOR-1.0-py3.7.egg/VISOR/VISOR.py", line 142, in main
    args.func(parser, args)
AttributeError: 'Namespace' object has no attribute 'func'
```
Thanks,
Zheng zhuqing

**Comment by davidebolo1993** [comment]
Hi @biozzq,

This is only because you called VISOR with no arguments. VISOR will work just fine if you provide the required subcommands with their parameters.

Best,

Davide
